Very good:

https://tech.aph.org/nemeth/

Not so good:

http://braillebug.afb.org/nemeth_braille.asp

With use cases:

http://www.tsbvi.edu/nemeth-code

Quite good:

http://www.gh-mathspeak.com/examples/NemethBook/


///
** Spaces after
*** DONE function applications (cos, sin),
*** DONE named infix operators like rem, mod (currently hardcoded)
*** TODO punctuation in lists etc.,
*** TODO denomination,
*** TODO ellipses.
** Around Arrows
** Endpunctuation with punctuation indicator.


** Numeric indicator
*** When first element (left most child) in an expression
*** What breaks a number declaration and leads to the need for re-declaration:
**** Relation signs (due to spaces)
**** Punctuation
**** Negative sign
**** Explicit font indicator (not sure yet how to do that!)

/// Too many number indicators!
<mfrac><mn>1</mn><mn>2</mn></mfrac>
⠹⠼⠂⠌⠼⠆⠼
sorge@zorkspecial:speech-rule-engine$ ./bin/sre -c nemeth -b braille
> <mfrac><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>x</mi></mfrac>
⠠⠹⠹⠼⠂⠌⠼⠆⠼⠠⠌⠭⠠⠼
sorge@zorkspecial:speech-rule-engine$ ./bin/sre -c nemeth -b braille
> <mfrac><mi>y</mi><mfrac><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>x</mi></mfrac></mfrac>
⠠⠠⠹⠽⠠⠠⠌⠠⠹⠹⠼⠂⠌⠼⠆⠼⠠⠌⠭⠠⠼⠠⠠⠼

<mrow><mo>-</mo><mn>3</mn></mrow>

<mrow><mi>sin</mi><mn>1</mn></mrow>

<mrow><mn>1</mn><mo>=</mo><mn>3</mn></mrow>

<mrow><mn>1</mn><mo>+</mo><mn>3</mn></mrow>

<mrow><mn>1</mn><mo>+</mo><mi>x</mi></mrow>

<mrow><mi>x</mi><mo>+</mo><mn>3</mn></mrow>


<mrow><mi>x</mi><mo>+</mo><mn>3</mn><mo>=</mo><mn>1</mn><mo>+</mo><mn>3</mn></mrow>

** Dot versus full stop etc. Ellipses need to be recognised better!
