let sre = require('speech-rule-engine');
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.setupEngine({locale: 'en', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-en.txt');
sre.setupEngine({locale: 'en', domain: 'clearspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-cs-en.txt');
sre.setupEngine({locale: 'fr', domain: 'mathspeak'});
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out.txt');
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-fr.txt');
sre.setupEngine({locale: 'fr', domain: 'clearspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-cs-fr.txt');
sre.setupEngine({locale: 'gg', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-gg.txt');
sre.setupEngine({locale: 'es', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-es.txt');
sre.setupEngine({locale: 'it', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-it.txt');
sre.setupEngine({locale: 'it', domain: 'clearspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-cs-it.txt');
sre.setupEngine({locale: 'de', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-de.txt');
sre.setupEngine({locale: 'de', domain: 'clearspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-cs-de.txt');
sre.setupEngine({locale: 'hi', domain: 'mathspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-ms-hi.txt');
sre.setupEngine({locale: 'hi', domain: 'clearspeak'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-cs-hi.txt');
sre.setupEngine({locale: 'nemeth', domain: 'default', modality: 'braille'});
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>x</mi><mo>=</mo><mfrac><mrow><mo>&#x2212;</mo><mi>b</mi><mo>&#xB1;</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>&#x2212;</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>'));
console.log(sre.toSpeech('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>&#x1D63C;</mi></math>'));
sre.file.toSpeech('/home/sorge/git/sre/sre-resources/samples/quadratic-line.xml', '/tmp/out-nemeth.txt');
console.log(sre.engineReady());
if (sre.exist) sre.exit();


